version: '2'
volumes:
  flagbot-postgresql:
    external: false
  pgadmin:
  redis:

services:

  bot:
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    networks:
      - postgres

  db:
    image: postgres:10-alpine
    volumes:
      - flagbot-postgresql:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_USER:-password}
    ports:
      - "5432:5432"
    networks:
      - postgres
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    logging:
      driver: none

  worker:
    build: .
    command: python -m worker
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./:/app
    networks:
      - postgres
    environment:
      - WORKER_COUNT=${WORKER_COUNT:-3}

  redis:
    image: redis:5-alpine
    command: redis-server --appendonly yes
    networks:
      - postgres
    volumes:
      - redis:/data

networks:
  postgres:
    driver: bridge
